version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./data:/var/www/data
      - ./scripts:/scripts
    environment:
      - SQLITE_DB_PATH=/var/www/data/midshelf.db
